42 maak een overzicht van alle producten inkoop
vampirewolfB/E3_Barroc_Intens_Team_Purple pull request #58
Opened 2024-12-16 09:29 UTC by sheepy-v2

het werkt de listview update alleen niet automatisch qua wanneer de instock wordt bijgevuld

2024-12-16 10:42 UTC, Tymuto approved these changes
Looks good

2024-12-16 10:43 UTC, vampirewolfB requested changes
On line 61 in ProductOverviewPage.xaml.cs there is a error.
Tabel looks a bit off with the headers and items.
Reset does reset the filter but not the drop-down for it. Also maybe some spacing there?

2024-12-17 09:26 UTC, vampirewolfB requested changes
Application crashes when I press the reset button.

2024-12-17 15:39 UTC, vampirewolfB approved these changes
All issues fixed and looks good now.

2024-12-17 15:39 UTC, merged